flask-todo/models.py
from todo import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    complete = db.Column(db.Boolean)

flask-todo/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    # bp 등록
    from .views import main_views
    app.register_blueprint(main_views.bp)

    return app

flask-todo/views/main_views.py
from flask import Blueprint, render_template, request, redirect, url_for
from todo.models import Todo
from todo import db

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    # show all todos
    todo_list = Todo.query.all()
    return render_template('base.html', todo_list=todo_list)

@bp.route('/add', methods=["POST"])
def add():
    # add new item
    title = request.form.get('title')
    new_todo = Todo(title=title, complete=False)
    db.session.add(new_todo)
    db.session.commit()
    return redirect(url_for('main.index'))

@bp.route('/update/<int:todo_id>') # /update/<int:todo_id> : 실행시 볼 수 없는 URI에서 코드 실행 후 반환
def update(todo_id):
    # update item
    todo = Todo.query.filter_by(id=todo_id).first()
    todo.complete = not todo.complete
    db.session.commit()
    return redirect(url_for('main.index'))

@bp.route('/delete/<int:todo_id>')
def delete(todo_id):
    # delete item
    todo = Todo.query.filter_by(id=todo_id).first()
    db.session.delete(todo)
    db.session.commit()
    return redirect(url_for('main.index'))

flask-todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=.10">
    <title>Todo App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
</head>
<body>
    <div style="margin-top:50px;" class="ui container">

        <div class="ui huge positive message">
          <h1 class="ui center aligned header">Todo App</h1>
        </div>

        <form class="ui form" action="{{ url_for('main.add') }}" method="post">
            <div class="field">
                <label style="font-size:1.2rem;" for="title">Todo Title</label>
                <input type="text" name="title" id="title" placeholder="Enter Todo...">
                <br>
                <button class="ui animated button" type="submit" tabindex="0">
                    <i class="caret up icon visible content"></i>
                  <span class="visible content">Add Todo</span>
                  <span class="hidden content">
                    <i class="right arrow icon"></i>
                  </span>
                </button>

                <div class="ui green basic label">
                  <i class="mail icon"></i> {{ todo_list|length }}
                </div>

            </div>
        </form>
            {% if todo_list|length == 0 %}
            <div class="ui card">
              <div class="image">
                <img src="./static/img/mini.jpg">
              </div>
              <div class="content">
                <a class="header">Gyeom</a>
                <div class="meta">
                  <span class="date">Made in 2023</span>
                </div>
                <div class="description">
                  Gyeom made Todo-app with Flask.<br>I learned sqlalchemy, migrate, post, get skills
                </div>
              </div>
              <div class="extra content">
                <a>
                  <i class="mail icon"></i>
                  {{ todo_list|length }}
                </a>
              </div>
            </div>
            {% endif %}
            {% for todo in todo_list %}
            <div class="ui segment">
                <p class="ui big header">{{ todo.id }} | {{ todo.title }}</p>
                {% if todo.complete == False %}
                <span class="ui gray label">Not Completed</span>
                {% else %}
                <span class="ui green label">Completed</span>
                {% endif %}

                <a class="ui blue animated button" tabindex="0" href="{{ url_for('main.update', todo_id=todo.id) }}">
                      <div class="visible content">Update</div>
                      <div class="hidden content">
                          <i class="sync alternate icon"></i>
                      </div>
                </a>
                <a class="ui yellow animated button" href="{{ url_for('main.delete', todo_id=todo.id) }}">
                    <div class="visible content">Delete</div>
                      <div class="hidden content">
                          <i class="chevron down icon"></i>
                      </div>
                </a>
            </div>
            {% endfor %}
    </div>
</body>
</html>